[package]
authors = ["Fabrice Desré <fabrice@desre.org>"]
edition = "2018"
license = "KaiOS"
name = "libsignal-sys"
publish = false
version = "0.1.0"

[dependencies]
aes = "0.8"
arrayref = "0.3"
block-modes = "0.9"
ctr = "0.9"
hmac = {version = "0.12", features = ["reset"]}
log = "0.4"
prost = "0.9"
prost-derive = "0.9"
ring = "0.16"
sha2 = "0.10"

[build-dependencies]
cc = "1.0"
prost-build = "0.9"
