[package]
authors = ["Fabrice Desré <fabrice@desre.org>"]
edition = "2018"
license = "AGPL-3.0-only"
name = "dweb_service"
version = "0.1.0"

[dependencies]
async-std = {version = "1.9", features = ["attributes"]}
base64 = "0.13"
chrono = "0.4"
common = {path = "../../common"}
did-key = {git = "https://github.com/capyloon/did-key.rs.git", rev = "3cd338a212444ded93a8cc95a4028cf46a32593f"}
lazy_static = "1.4"
log = "0.4"
parking_lot = "0.12"
serde = "1.0"
serde_json = "1.0"
thiserror = "1.0"
tokio = "1"

[build-dependencies]
common = {path = "../../common"}
