name: Rust

on: [push, pull_request]



jobs:
  build:
    strategy:
      matrix:
        toolchain: ["1.34.0", "1.42.0", "stable", "beta", "nightly"]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install toolchains
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.toolchain }}

    - name: Build
      run: cargo +${{ matrix.toolchain }} build --verbose
    - name: Run tests
      run: cargo +${{ matrix.toolchain }} test --verbose

    - name: Run more tests
      if: matrix.toolchain != '1.34.0'
      run: cargo +${{ matrix.toolchain }} test -p --manifest-path procfs-tests/Cargo.toml -p procfs-tests

    - name: Build docs (all features)
      if: matrix.toolchain != '1.34.0'
      run: cargo +${{ matrix.toolchain }} doc --all-features

    - name: Build docs
      if: matrix.toolchain == '1.34.0'
      run: cargo +${{ matrix.toolchain }} doc


  android-check:
    strategy:
      matrix:
        toolchain: ["1.42.0", "stable", "beta", "nightly"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install toolchains
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          target: aarch64-linux-android

      - name: cargo check
        run: cargo +${{ matrix.toolchain }} check --target aarch64-linux-android

